import Vue from 'vue'
import { Button, Row, Col, Message, MessageBox, Container, Header, Aside, Main, Menu, Submenu, MenuItem, Carousel, CarouselItem, Input, Breadcrumb, BreadcrumbItem, Tag, Form, FormItem, Avatar, Card, Badge, Upload, Image, Table, TableColumn, Pagination, Switch, Dialog } from 'element-ui'

Vue.use(Button)
Vue.use(Row)
Vue.use(Col)
Vue.use(Container)
Vue.use(Aside)
Vue.use(Header)
Vue.use(Main)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Input)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Tag)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Avatar)
Vue.use(Card)
Vue.use(Badge)
Vue.use(Upload)
Vue.use(Image)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Pagination)
Vue.use(Switch)
Vue.use(Dialog)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
